`$default` arm  in switch
json-e/json-e pull request #456
Opened 2022-12-04 21:52 UTC by noahlaux

This change introduces a `$default` fallback case as suggested in #455.

# Checklist

Before submitting a pull request, please check the following:

* [X] All tests pass for you on your machine for all implementations (all implementations must behave identically)
* [X] New tests have been added for any new functionality or to prevent regressions of a bugfix
* [X] Added a short description of the change to `newsfragments/$issue.bugfix` (for fixes) or `.feature` (for new features) or `.doc` (for documentation-only changes)

2022-12-05 23:36 UTC, djmitche requested changes
This looks good, with just a performance note for the Rust implementation.

2022-12-05 23:36 UTC, djmitche commented on rs/src/render.rs
> +    let mut value_without_default = value.clone();
Is there a way to avoid this `clone`?  Perhaps by modifying `get_matching_conditions` to skip `$default`?

It looks like there might be an unrelated bug here, which is that the Rust implementation eagerly renders all of the object values, while the other implementations only render the value with the truthy key.  But that could be addressed in another PR.

2022-12-06 00:12 UTC, djmitche commented on rs/src/render.rs
> +    let mut value_without_default = value.clone();
Hm, I didn't realize that either.  It seems it's used for $match and $switch, which are pretty similar.  Maybe add an `ignore_default: bool`?

2022-12-06 00:21 UTC, noahlaux commented on rs/src/render.rs
> +    let mut value_without_default = value.clone();
fixed in https://github.com/json-e/json-e/pull/456/commits/af38ab24452ed2e380c44ea353a64cdf454fda40

2022-12-06 00:32 UTC, djmitche commented
Hm, those rust tests are actually failing, but I see that CI is only running `mdbook test`.  There are also three rust tests failing on `main`! :(

I can make up a PR to fix that.  But, looking at the failures, I think to support $default we may need to solve the other issue I noted -- `_render(..)`ing the entire object before checking the conditions.

2022-12-06 00:37 UTC, noahlaux commented
ahh, I was relying on the CI tests, I can see now when running the tests locally, sorry :(

2022-12-06 00:40 UTC, djmitche commented
No worries!  https://github.com/json-e/json-e/pull/457 should fix CI.

2022-12-06 01:15 UTC, noahlaux commented
@djmitche Do you think the eager rendering is part of another PR? It also takes place in the `$match` operator?

2022-12-06 01:23 UTC, djmitche commented
If it needs to be solved to fix this issue (and I think that's the case, but maybe not!) then it's OK to do it in this PR.

2022-12-06 01:54 UTC, djmitche commented
I'm happy to help, too..

2022-12-06 01:57 UTC, noahlaux commented
cool, so basically I think my hurdle would be deferring the rendering without plastering with clones and unwrapping, and also looking into the nice simplicity of the pattern matching in fx the `$if` operator.

2022-12-06 02:05 UTC, djmitche commented
I think one important step would be to make `get_matching_conditions` take `&Object` so that the object can still be used later.  It can return `Result<Vec<&Value>>`, I think?  Then, if it returns something of interest, it's up to the caller to call `_render(v)` for each `&Value` in that vector.

2022-12-22 16:15 UTC, djmitche commented
@noahlaux I made the rust refactor -- let me know what you think?

2022-12-23 21:13 UTC, noahlaux commented
Hey @djmitche, I was out traveling and didn't check here :( sorry for not communicating properly. 

Your refactor is stellar, way better than something I could come up with! Let's go with that and thanks for chipping in!

2022-12-24 14:43 UTC, djmitche commented
Awesome, thanks for taking a look!  It's always more fun to collaborate :)

2022-12-24 14:44 UTC, djmitche approved these changes

2022-12-24 14:44 UTC, merged

2022-12-24 15:03 UTC, noahlaux commented
@djmitche exactly! Merry Christmas to you (if you celebrate)

2022-12-25 04:58 UTC, ahal commented
Thank you very much for implementing this! Will result in a huge improvement in our `.taskcluster.yml` files :)

2022-12-25 08:37 UTC, noahlaux commented
You’re welcome, I have quite some files that will benefit as well

2022-12-25 19:06 UTC, djmitche commented
Now available in json-e 4.5.0.