add tests found while developing .net implementation
json-e/json-e pull request #502
Opened 2023-11-24 21:43 UTC by gregsdennis

These are tests that I found while developing a .Net implementation for my `json-everything` project.

Ref: https://github.com/gregsdennis/json-everything/pull/566

I'm not set up to run the existing implementations, but I expect they should handle these tests.

# Checklist

Before submitting a pull request, please check the following:

* [ ] All tests pass for you on your machine for all implementations (all implementations must behave identically)
* [x] New tests have been added for any new functionality or to prevent regressions of a bugfix
* [ ] Added a short description of the change to `newsfragments/$issue.bugfix` (for fixes) or `.feature` (for new features) or `.doc` (for documentation-only changes)

2023-11-25 20:17 UTC, djmitche reviewed
I pushed some commits to fix all of the failing tests except the map-overwrite test.

2023-11-25 20:17 UTC, djmitche commented on specification.yml
> +result:   {foo: 4}
This is currently non-deterministic, and will fail about 2/3 of test runs in languages that randomize object order. JS maintains object insertion order, so it's passing for the JS implementation.

I think this should be treated as an error, rather than randomly selecting one of the keys to win.  I'm curious what your implementation is doing -- selecting the lexically greatest key? Or does it also maintain object insertion order?

2023-11-25 20:20 UTC, gregsdennis commented on specification.yml
> +result:   {foo: 4}
My implementation passes all of these new tests.  .Net uses insertion order.

2023-11-25 20:21 UTC, gregsdennis commented
All of these tests were checked in the playground, so I guess that's just the JS implementation.

2023-11-25 20:22 UTC, djmitche commented on specification.yml
> +result:   {foo: 4}
Got it. Insertion order isn't generally defined for JSON data structures, so we'll need to find some other way to define this. I'd lean toward making it an error, but we could also consider the keys in lexical order. The latter is the fix we did for $map when we realized it was relying on insertion order.

2023-11-27 04:24 UTC, gregsdennis commented
I added another test.  This one ensures the result of a function call can be the target of an accessor.  My implementation doesn't support this currently (will fix), but the playground does.

2023-11-27 17:49 UTC, djmitche commented
Hm, maybe we can move that new test to a new PR, since the Rust implementation fails, too?

2023-11-28 00:16 UTC, djmitche requested changes

2023-11-28 00:16 UTC, djmitche commented on specification.yml
> +result:   {foo: 4}
We still need to resolve this..

2023-12-02 20:06 UTC, djmitche approved these changes

2023-12-02 20:10 UTC, merged