Add a `$reduce` operator
json-e/json-e pull request #531
Opened 2024-09-13 16:57 UTC by tadpol

This adds a `$reduce` operator.  It is somewhat similar to the `$merge` operator expect that it can produce any valid JSON type, not just objects.

As a simple example:
```yaml
$reduce: [2, 4, 6]
each(acc, x): "${acc}${x}"
initial: 'pre '
```

Will output: `pre 246`

I am submitting this as a draft for now because:
1. I would like some feedback on this operator.
2. Only the Javascript version is implemented.
3. No docs yet.

# Checklist

Before submitting a pull request, please check the following:

* [X] All tests pass for you on your machine for all implementations (all implementations must behave identically)
* [X] New tests have been added for any new functionality or to prevent regressions of a bugfix
* [ ] Added a short description of the change to `newsfragments/$issue.bugfix` (for fixes) or `.feature` (for new features) or `.doc` (for documentation-only changes)

2024-09-14 19:39 UTC, noahlaux commented
Hi @tadpol, first of all thanks for contributing to the project! I feel strongly for functional programming so I'm totally with you, I even contributed a couple of operators to json-e which is normally to be found in functional programming languages, fx [find](https://github.com/json-e/json-e/issues/525).

As you can read in the issue, it was possible to actually do what I wanted with the existing operators, but it was slightly cumbersome and verbose. I actually thought about suggesting a `reduce` as well, but I couldn't come up with a good use case for it that wasn't possible just using the existing operators.

I was also thinking about making a filter function, but in fact since json-e omit null values in the [$map](https://json-e.js.org/operators.html#map) operator, the overhead of just adding a [$if](https://json-e.js.org/operators.html#if---then---else) doesn't seem to much of a deal.

```yaml
# A potential filter function
$filter: [1, 2, 3]
each(value): value > 1
```

```yaml
# How you can already do in json-3
$map: [1, 2, 3]
each(value):
  $if: value > 1
  then:
    $eval: value
```

Looking at your (granted) quite simple example, it seems to me like:

1. There are already ways to achieve that with the existing operators and it might even be simpler

  Using existing builtin functionality in json-e:

  ```yaml
  # Example 1 with inline
  pre ${join([2, 4, 6],'')} # => pre 246
  ```

  ```yaml
  # Example 2 with context
  template: pre ${join(value, '')}
  context:
    value: [2, 4, 6]
  ```

  ```yaml
  # Example 3 with $let
  $let:
    value: [2, 3, 4]
  in: pre ${join(value,'')}
  ```

1. I my mind, as a programmer, and knowing reduce from other language, your example should yield `pre 6`. It's unclear why `${x}` is being joined while `${acc}` isn't. I would expect the `each` function to be called with the accumulator and the current value, and the result of the function to be the new accumulator. This is how reduce works in other languages I know of.

Maybe I'm wrong but I'd love to understand how you think the inner workings of the reduce should work and maybe you could come up with some more advanced examples where the existing operators can't do the job.

2024-09-14 20:34 UTC, tadpol commented
Agreed, most of the simple examples for `$reduce` can be already done in json-e.  It is just that the simple examples are the easiest to explain how it works.

> I would expect the each function to be called with the accumulator and the current value, and the result of the function to be the new accumulator. This is how reduce works in other languages I know of.

That is how I understand reduce to work and was my intention in the simple example.  Maybe I made I mistake typing it?

Why I'm proposing this is for a more complex use case.  I'll just show the real world I'm dealing with.  I tried for a while to figure out to do this already in json-e. However because of my specific use case, while I could solve it with many nested `$let`s it is visually unappealing.  In most other tooling, a reduce function of some kind is what I would have used. (or worse global variables, or slightly better a captured scope)

The shape of the context in this case is fixed.  So many of the things I'm trying to fix could be solved if I could change the context, but I can't.  There is other stuff in there (and in the template), but for what I want a `$reduce` for, here is just what is relevant.  There are 9 keys, five can hold numbers or undefined, four hold strings.  The four strings are the basic math operations.  (The system that calls the json-e deals with making sure all of the undefined number keys are "at the end", and are aligned with the op keys.)

An example context with all nine keys filled:
```json
{
 "A": 10,
 "B": 2,
 "C": 8,
 "D": 1,
 "E": 1,
 "opA": "+",
 "opB": "+",
 "opC": "/",
 "opD": "+"
}
```

Now I need a bit of json-e to take that mess and produce a single number using the math operations provided.  If the `$reduce` operation existed, I could do this:

```yaml
$let:
  values:
    $map:
      $eval: '[B,C,D,E]'
    'each(v)':
      $if: defined(v)
      then:
        eval: v
  ops:
    $eval: '[opA,opB,opC,opD]'
in:
  $reduce: values
  initial:
    $eval: 'A'
  'each(a,v,i)':
    $switch:
      'ops[i] == "+"':
        $eval: 'a + v'
      'ops[i] == "-"':
        $eval: 'a - v'
      'ops[i] == "*"':
        $eval: 'a * v'
      'ops[i] == "/"':
        $eval: 'a / v'
      $default:
        $eval: a

```

This is still a bit of a mess, but it is cleaner than the four layer nested `$let` mess I have currently.

2024-09-15 05:43 UTC, noahlaux commented
@tadpol after reading my answer again yesterday, I had to r remove quite a bit because I had misunderstood the inner workings of your proposal. I'm sorry you had to take time to explain something that was already clear!

Now, with your second example I can see why `reduce` makes sense indeed. I also tried to think about other ways to solve your particular problem, but wasn't able to come up with something better.

2024-09-16 00:37 UTC, djmitche commented
I'm happy to see this conversation! As a meta-point, please be careful editing posts, and try to limit those edits to not modify the meaning, and use ~~strikeout~~ to indicate that some parts have been repudiated, e.g., "~~the sky is green~~ [edit: see below where I was reminded that it is, in fact, blue]". Otherwise it's confusing for later readers to see a reply to a message different from the one appearing in the issue.

2024-09-16 10:48 UTC, noahlaux commented
> I'm happy to see this conversation! As a meta-point, please be careful editing posts, and try to limit those edits to not modify the meaning, and use ~strikeout~ to indicate that some parts have been repudiated, e.g., "~the sky is green~ [edit: see below where I was reminded that it is, in fact, blue]". Otherwise it's confusing for later readers to see a reply to a message different from the one appearing in the issue.

@djmitche I totally agree! I did realize my wrongful statements rather quickly and I thought I could spare @tadpol to even think about it by removing, but he was very quick :)

2024-09-26 13:46 UTC, noahlaux commented on js/src/index.js
> +  let eachKey = Object.keys(template).filter(k => k !== '$reduce' && k !== 'initial')[0];
I suppose you could just use a find here

```suggestion
  let eachKey = Object.keys(template).find(k => k !== '$reduce' && k !== 'initial');
```

2024-09-26 13:53 UTC, noahlaux requested changes

2024-09-26 13:53 UTC, noahlaux commented on js/src/index.js
> +  }
Keeping it DRY

```suggestion
  value = isObject(value) ? Object.keys(value).map(key => ({key, val: value[key]})) : value;

  return value.reduce((acc, v) => {
    let args = typeof i !== 'undefined' ? {[a]: acc, [x]: v.val, [i]: v.key} : {[a]: acc, [x]: v};
    const r = render(each, Object.assign({}, context, args));
    return r === deleteMarker ? acc : r;
  }, initialValue);
```

2024-09-26 13:55 UTC, noahlaux commented on py/jsone/newsfragments/+reduce.feature
> +Introduces the `$reduce` operator which combines an array or object into a single JSON value.
Introduces the `$reduce` operator which accumulates an array or object into a single value.

2024-09-26 18:11 UTC, gregsdennis commented on docs/src/operators.md
> +  each(acc, v, k):
There may be some implementation consistency issues here.  Some languages don't iterate over objects in a deterministic way.  We've seen in JSON Schema where iteration over objects produces the children in varying orders even within the same language sometimes.  Depending on the function, that could produce different results with each run.

2024-09-26 19:03 UTC, tadpol commented on docs/src/operators.md
> +  each(acc, v, k):
Yes.  I am assuming that when iterating over objects the order is non-deterministic.  And that when using `$reduce` people will take this into account.

2024-09-26 19:19 UTC, noahlaux commented on docs/src/operators.md
> +  each(acc, v, k):
Yeah the order can't be trusted, it's also left out in iteration over objects in [maps](https://json-e.js.org/operators.html#over-objects). So maybe for consistency we should leave it out?

2024-09-27 01:39 UTC, djmitche requested changes
This is looking great!

2024-09-27 01:39 UTC, djmitche commented on docs/src/operators.md
> +the result of the prior expression.  Reducing the array or object into a single JSON value.
```suggestion
the result of the prior expression, reducing the array or object into a single JSON value.
```

2024-09-27 01:39 UTC, djmitche commented on docs/src/operators.md
> +An initial result is passed in for the first evaluation of the expression.
```suggestion
An initial value is passed as the accumulator for the first evaluation of the expression.
```

2024-09-27 01:39 UTC, djmitche commented on docs/src/operators.md
> +  $reduce: A
```suggestion
  $reduce: {$eval: "A"}
```

2024-09-27 01:39 UTC, djmitche commented on docs/src/operators.md
> +  each(acc, v, k):
It isn't that $map doesn't specify order. Order of object keys is simply not defined, in the sense that two objects are equal if every key/value pair in one is also in the other. So, $map is deterministic: given an object, it produces an object.

We should avoid anywhere where the implementation detail of the order in which iteration occurs over an object has an effect on the results, rather than relying on the template author to ensure this. Otherwise two renderings of the same template with the same context could sometimes have different results, which would cause all manner of intermittent bugs.

In this case, I think that restriction requires either defining the order in which that iteration occurs (sorted keys), or simply not defining the operator over objects. Since we already have $sort, I would lean toward the latter.

2024-09-27 01:39 UTC, djmitche commented on docs/src/operators.md
> +An initial result is passed in for the first evaluation of the expression.
Also it might be worth mentioning that this is also known as "fold" or "accumulate", just in case that matches the term from users' preferred language.

2024-09-27 01:39 UTC, djmitche commented on rs/src/op_props.rs
> +    let (input, _) = multispace0(input)?;
I'm curious why this was required? Were there expressions that didn't parse without it?

2024-09-27 01:39 UTC, djmitche commented on specification.yml
> +result: 8
Please add some error cases as well: passing disallowed types to `$reduce`, omitting `initial`, and malformed `each`.

2024-09-27 02:08 UTC, gregsdennis commented on docs/src/operators.md
> +An initial result is passed in for the first evaluation of the expression.
"aggregate" is another one I see a lot

2024-09-27 02:15 UTC, gregsdennis commented on docs/src/operators.md
> +  each(acc, v, k):
My concern was heightened when I saw [this comment and use case](https://github.com/json-e/json-e/pull/531#issuecomment-2351144096).  Looking at it again, it looks like all of the orderings are explicitly specified by the embedded arrays, but it's not a long leap to end up with something that depends on key selection order.

2024-09-27 12:30 UTC, djmitche commented on docs/src/operators.md
> +  each(acc, v, k):
I believe Python at least randomizes the order of its maps, so if we do introduce a dependency on order hopefully tests will find it.

2024-09-27 13:12 UTC, tadpol commented on rs/src/op_props.rs
> +    let (input, _) = multispace0(input)?;
The implementations for js, py, and go all handle the each function for map with spaces after the comma.  Rust is the only one that didn't. So js, py, go: `each(x, i)` or `each(x,i)`, and rust only `each(x,i)`.

Arguably, I can see this as a separate bug that could be in its own PR.

2024-09-27 13:13 UTC, tadpol commented on rs/src/op_props.rs
> +    let (input, _) = multispace0(input)?;
…and I'm the type of person that habitually puts a space after a comma, and that's the way I wrote the `$reduce` tests in specification.yaml

2024-09-27 13:30 UTC, tadpol commented on docs/src/operators.md
> +  each(acc, v, k):
It certainly would be clearer to have `$reduce` only work over arrays.  The only reason I included working over objects is that I started the `$reduce` code by copying the `$map` code.

2024-09-29 20:46 UTC, djmitche commented on rs/src/op_props.rs
> +    let (input, _) = multispace0(input)?;
Oh, good catch! And, those `$reduce` tests will serve as a regression test for this.

Another issue/PR would have been nice for archaeological purposes (such as someone trying to figure out when this was fixed), but it's done and now it's been discussed here so I think it's fine as-is.

2024-09-29 20:48 UTC, djmitche commented on docs/src/operators.md
> +  each(acc, v, k):
Let's do that (only work over arrays).

If it becomes necessary, we can discuss how to best support `$reduce` over objects at that time.

2024-09-30 23:14 UTC, gregsdennis commented on docs/src/operators.md
> +  each(acc, v, k):
@tadpol you marked this as resolved, but I still see iterating over objects in the docs.

2024-10-01 01:43 UTC, tadpol commented on docs/src/operators.md
> +  each(acc, v, k):
Oh for. I completely forgot to update the docs. Thanks for catching that.

2024-10-01 18:44 UTC, gregsdennis commented
(Force pushes make it difficult to see progression.  But this isn't my repo.)

2024-10-01 18:47 UTC, gregsdennis commented on docs/src/operators.md
> +the result of the prior expression, reducing the array or object into a single JSON value.
Still has language about iterating over objects.

2024-10-01 18:47 UTC, gregsdennis commented on docs/src/operators.md
> +This operation is sometimes called `fold`, `accumulate`, `aggregate`, `reduce`, or `inject`.
Do we need to repeat "reduce" in this list?

2024-10-02 17:21 UTC, gregsdennis commented on docs/src/operators.md
> +the result of the prior expression, reducing the array or object into a single JSON value.
"array or object"

2024-10-02 22:43 UTC, djmitche commented
I'm happy to merge once the last vestiges of objects in the doc are eliminated..

2024-10-03 17:20 UTC, gregsdennis approved these changes

2024-10-03 17:20 UTC, gregsdennis commented
🎉❤️

2024-10-03 21:34 UTC, djmitche approved these changes

2024-10-03 21:34 UTC, merged

2024-10-03 21:44 UTC, djmitche commented
v4.8.0 is released!